# Generated by Django 4.1.13 on 2024-01-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='headline',
            new_name='todo',
        ),
    ]
